services:
  # 服务名
  metar-service:
    # 使用的镜像
    image: halfnothing/metar-service:latest
    # 容器名称
    container_name: metar-service
    # 端口映射
    # 宿主机端口:容器端口
    networks:
      - main
    ports:
      - "8080:8080"
    # 挂载卷列表
    volumes:
      - ./logs:/metar-service/logs
      - ./config.yaml:/metar-service/config.yaml
    # 重启模式
    restart: always

networks:
  main:
    driver: bridge