name: Go-Build

on:
  push:
    branches:
      - "main"
    paths:
      - .github/workflows/**
      - src/**
      - main.go
      - go.mod
  pull_request:
    branches:
      - "main"
  workflow_dispatch:


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Set short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Build
        run: go build -ldflags="-w -s" -tags "http" -o metar-service-linux-${{ env.SHORT_SHA }} .
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Compress executable file
        run: upx -fq -9 ./metar-service-linux-${{ env.SHORT_SHA }}
      - uses: actions/upload-artifact@v4
        with:
          name: linux-nightly
          path: ./metar-service-linux-${{ env.SHORT_SHA }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -ldflags="-w -s" -tags "http" -o metar-service-windows-${{ github.sha }}.exe .
      - name: Run UPX
        uses: crazy-max/ghaction-upx@v3
        with:
          version: latest
          install-only: true

      - name: Compress executable file
        run: upx -fq -9 ./metar-service-windows-${{ github.sha }}.exe
      - uses: actions/upload-artifact@v4
        with:
          name: windows-nightly
          path: ./metar-service-windows-${{ github.sha }}.exe